### ISSUE TITLE
Colorwheel/Flywheel shaders fail to compile with Solas 3.5+ on Create objects

### ISSUE THREAD

**Issue by u7f8au7fbd** [djefrey/Colorwheel#66]
<img width="1339" height="757" alt="Image" src="https://github.com/user-attachments/assets/b0eafce5-0f0d-48c2-bd67-214616df46db" />
# Colorwheel/Flywheel support appears broken with Solas 3.5+ on Create objects

## Summary

Create/Flywheel-rendered objects are no longer rendered correctly when using **Solas Shader V3.5 or later** together with **Colorwheel**.

The client log shows that Colorwheel generates a Flywheel/Create shader which fails to compile due to a duplicate `ao` declaration:

```txt
error C1038: declaration of "ao" conflicts with previous declaration
```

The failing generated shader appears to be:

```txt
clrwl_gbuffers/create_instance_rotating/flywheel_material_default_default.fsh
```

This looks like a regression in the Solas 3.5+ shader source or its interaction with Colorwheel's Flywheel compatibility layer.

## Environment

- Minecraft: `1.21.1`
- NeoForge: `21.1.228`
- Java: `21.0.7`
- GPU: `NVIDIA GeForce RTX 2080 Ti`
- GPU Driver: `NVIDIA 596.21`
- Iris: `1.8.12+mc1.21.1`
- Sodium: `0.6.13+mc1.21.1`
- Solas Shader: `V3.5`
- Colorwheel: `1.2.5+mc1.21.1`
- Colorwheel Patcher: `1.0.5+mc1.21.1`
- Create: `6.0.10`
- Flywheel: `1.0.6`
- Ponder: `1.0.82+mc1.21.1`

## Relevant mods

```txt
colorwheel-neoforge-1.2.5+mc1.21.1.jar
colorwheel_patcher-neoforge-1.0.5+mc1.21.1.jar
create-1.21.1-6.0.10.jar
sodium-neoforge-0.6.13+mc1.21.1.jar
iris-neoforge-1.8.12+mc1.21.1.jar
```

Create bundles:

```txt
flywheel-neoforge-1.21.1-1.0.6.jar
ponder-neoforge-1.0.82+mc1.21.1.jar
```

## Actual behavior

Create objects rendered through Flywheel/Colorwheel are rendered incorrectly or fail to render properly.

The log shows that Flywheel falls back to the Colorwheel instancing backend:

```txt
Flywheel backend fell back from 'flywheel:indirect' to 'colorwheel:instancing'
```

Then Colorwheel fails to compile a generated shader:

```txt
Could not compile shader
```

The specific GLSL error is:

```txt
error C1038: declaration of "ao" conflicts with previous declaration
```

The generated shader path in the log is:

```txt
clrwl_gbuffers/create_instance_rotating/flywheel_material_default_default.fsh
```

## Expected behavior

Create/Flywheel objects should render correctly with Colorwheel enabled when using Solas Shader.

## Regression

This appears to happen starting from **Solas Shader V3.5**.

Solas versions before 3.5 did not appear to have this issue in the same setup.

## Log excerpt

```txt
Using shaderpack: Solas Shader V3.5.zip
[colorwheel/]: Is OIT supported: true

Flywheel backend fell back from 'flywheel:indirect' to 'colorwheel:instancing'

error C1038: declaration of "ao" conflicts with previous declaration

Could not compile shader
clrwl_gbuffers/create_instance_rotating/flywheel_material_default_default.fsh
```

## Notes

Colorwheel Patcher also prints:

```txt
Solas Shader V3.5.zip []
Could not find patch for Solas Shader V3.5.zip
```

However, Solas is listed as officially supported by Colorwheel, so I am not sure whether this is relevant or just expected behavior for this shaderpack.

The core issue seems to be the generated Flywheel/Create shader failing due to the duplicate `ao` declaration.

## Attachments

I can provide the full `latest.log` if needed.

**Comment by djefrey** [comment]
That's a Solas issue which has already been reported
https://github.com/Septonious/Solas-Shader/issues/160
